### ISSUE TITLE
Use SELinux calls for this rather then execing chcon.  setfilecon

### ISSUE THREAD

**Issue by rhatdan** [tchughesiv/oci-uid-hook#6]
asprintf(&chcon_command, "chcon %s %s", mlabel, newPasswdNew);
	system(chcon_command);
	chmod(newPasswdNew, 0644);

**Comment by rhatdan** [comment]
man setfilecon()

#include <selinux/selinux.h>
if (setfilecon (newPasswdNew, mlabel) < 0) {
	pr_perror("Failed to set context %s on %s", newPasswdNew, mlabel);
}

**Comment by rhatdan** [comment]
Also only do this if mlabel != "".

**Comment by tchughesiv** [comment]
nice, was hoping there was a way without system call

**Comment by tchughesiv** [comment]
resolved w/ #8
