### ISSUE TITLE
Since you are checking for -lselinux, you should use #ifdef HAVE_SELINUX around SELinux blocks.

### ISSUE THREAD

**Issue by rhatdan** [tchughesiv/oci-uid-hook#9]

**Comment by tchughesiv** [comment]
#10 should resolve... thanks

**Comment by tchughesiv** [comment]
I'll clean it up a bit more once this commit is merged...
https://github.com/tchughesiv/oci-uid-hook/commit/21173a751f07ecbc3f0b8b74ae9150439138ff18
